CREATE TABLE SALLE
(
IDsalle INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nomSalle VARCHAR(10) NOT NULL,
capacite INT(3)
);

CREATE TABLE CLIENT
(
IDclient INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nom_client VARCHAR(10),
prenom_client VARCHAR(10),
email VARCHAR(80)
);

CREATE TABLE FILM
(
IDfilm INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
titre VARCHAR(30) NOT NULL,
datesortie INT(4),
duree INT(3),
genre VARCHAR(30)
);

CREATE TABLE PERSONNE
(
IDpersonne INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nompersonne VARCHAR(20) NOT NULL,
prenompersonne VARCHAR(20),
datenaissance INT(4)
);

CREATE TABLE AVIS
(
NumAvis int NOT NULL AUTO_INCREMENT PRIMARY KEY,
Note INT(1) NOT NULL,
IDfilm INT(5) REFERENCES FILM,
IDclient INT(5) REFERENCES CLIENT
);


CREATE TABLE JOUE
(
IDjoue INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
roleact VARCHAR(20) NOT NULL,
IDfilm INT(5) REFERENCES FILM,
IDpersonne INT(5) REFERENCES PERSONNE
);

CREATE TABLE REALISE
(
IDreal INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
IDpersonne INT(5) REFERENCES PERSONNE,
IDfilm INT(5) REFERENCES FILM
);



CREATE TABLE SEANCE
(
IDseance INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
date_seance DATETIME,
type_seance VARCHAR(10),
langue VARCHAR(2),
prix_billet INT(2),
IDsalle INT(5) REFERENCES SALLE,
IDfilm INT(5) REFERENCES FILM
);



CREATE TABLE RESERVATION
(
    IDres INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
    IDclient INT(5) REFERENCES CLIENT,
    IDseance INT(5) REFERENCES SEANCE
)